engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - app/**
  - "**.js"
exclude_paths:
- tests/**/*
- docs/**/*
- vendor/**/*
- public/**/*
