site_name: pilas-engine

pages:
- "Principal": "index.md"
#- "Tipos de juegos": "que_juegos.md"
#- "Instalación": "instalacion.md"
#- "Acerca de ...": "about.md"
#- "Empezando y los primeros pasos con pilas": "empezando.md"
#- "Actores": "actores.md"
#- "Actores personalizados": "actores_personalizados.md"
#- "Grupos": "grupos.md"
#- "Colisiones": "colisiones.md"
#- "Etiquetas": "etiquetas.md"
#- "Fisica": "fisica.md"
#- "Controles": "controles.md"
#- "Joystick": "joystick.md"
#- "Imagen": "imagen.md"
#- "Sonidos": "sonidos.md"
#- "Dibujado simple en pantalla": "dibujado_simple_en_pantalla.md"
#- "Dibujado avanzado con Superficies": "dibujado_avanzado_con_superficies.md"
#- "Manejo de tiempo con tareas": "tareas.md"
#- "Interpolaciones": "interpolacion.md"
#- "Controlando la pantalla": "controlando_la_pantalla.md"
#- "Comportamientos": "comportamientos.md"
#- "Escenas": "escenas.md"
#- "Interfaz de usuario": "interfaz.md"
#- "Cómo crear menúes para tu juegos": "menu.md"
#- "Mapas y plataformas": "mapas_y_plataformas.md"
#- "Diálogos": "dialogos.md"
#- "Manejo de Cámara": "camara.md"
#- "Eventos": "eventos.md"
#- "Textos": "texto.md"
#- "Habilidades": "habilidades.md"
#- "Depurando": "depurando.md"
#- "¿Cómo funciona pilas por dentro?": "como_funciona_pilas_por_dentro.md"
#- "Complementos": "complementos.md"
#- "Guía para desarrolladores": "desarrolladores.md"

theme_dir: 'custom_theme'
theme: 'readthedocs'
